### ISSUE TITLE
 issue installation with windows python 3.12

### ISSUE THREAD

**Issue by rimsila** [seanghay/tha#1]
I have issue installation with windows python 3.12 , pip install tha

![image](https://github.com/seanghay/tha/assets/51617383/f8c49fff-9648-4cb4-9ff5-b23351e61d79)

I think it error because of README content contain utf-8

I have tried this it working 
```bash
with open("README.md", encoding="utf-8") as f:
  long_description = f.read()
  ```

**Comment by seanghay** [comment]
@rimsila I don't have Windows device to test the issue. I think you should use Windows Subsystem for now.
